"""create parking tables

Revision ID: 1ce832239fa5
Revises: fe4b60ff4236
Create Date: 2026-09-27 22:08:08.863342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce832239fa5'
down_revision: Union[str, Sequence[str], None] = 'fe4b60ff4236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'code', name='uq_slot_society_code')
    )
    op.create_index(op.f('ix_parking_slots_id'), 'parking_slots', ['id'], unique=False)
    op.create_index(op.f('ix_parking_slots_occupancy_id'), 'parking_slots', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_parking_slots_society_id'), 'parking_slots', ['society_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('parking_code', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'vehicle_number', name='uq_vehicle_society_number')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_occupancy_id'), 'vehicles', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_vehicles_slot_id'), 'vehicles', ['slot_id'], unique=False)
    op.create_index(op.f('ix_vehicles_society_id'), 'vehicles', ['society_id'], unique=False)
    op.create_table('visitor_parkings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('parking_code', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_parkings_id'), 'visitor_parkings', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_parkings_occupancy_id'), 'visitor_parkings', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_visitor_parkings_slot_id'), 'visitor_parkings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_visitor_parkings_society_id'), 'visitor_parkings', ['society_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_visitor_parkings_society_id'), table_name='visitor_parkings')
    op.drop_index(op.f('ix_visitor_parkings_slot_id'), table_name='visitor_parkings')
    op.drop_index(op.f('ix_visitor_parkings_occupancy_id'), table_name='visitor_parkings')
    op.drop_index(op.f('ix_visitor_parkings_id'), table_name='visitor_parkings')
    op.drop_table('visitor_parkings')
    op.drop_index(op.f('ix_vehicles_society_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_slot_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_occupancy_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_parking_slots_society_id'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_occupancy_id'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_id'), table_name='parking_slots')
    op.drop_table('parking_slots')
    # ### end Alembic commands ###
