"""update the society model

Revision ID: b6188159b5a9
Revises: d6b77c28b131
Create Date: 2026-09-24 11:49:20.651392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6188159b5a9'
down_revision: Union[str, Sequence[str], None] = 'd6b77c28b131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('registration_number', sa.String(length=80), nullable=True))
    op.add_column('societies', sa.Column('society_type', sa.String(length=50), nullable=True))
    op.add_column('societies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('societies', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('societies', sa.Column('state', sa.String(length=80), nullable=True))
    op.add_column('societies', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('societies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('societies', sa.Column('contact_number', sa.String(length=20), nullable=True))
    op.alter_column('societies', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_unique_constraint(None, 'societies', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_societies_registration_number', 'societies', type_='unique')
    op.alter_column('societies', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('societies', 'contact_number')
    op.drop_column('societies', 'email')
    op.drop_column('societies', 'pincode')
    op.drop_column('societies', 'state')
    op.drop_column('societies', 'city')
    op.drop_column('societies', 'address')
    op.drop_column('societies', 'society_type')
    op.drop_column('societies', 'registration_number')
    # ### end Alembic commands ###
