"""add module of visitor

Revision ID: cba30155edaf
Revises: 2acacf31cb7c
Create Date: 2026-09-27 08:35:55.918570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba30155edaf'
down_revision: Union[str, Sequence[str], None] = '2acacf31cb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_society_id'), 'visitors', ['society_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('visitor_type', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_preapproved', sa.Boolean(), nullable=False),
    sa.Column('rejected_by', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_occupancy_id'), 'visits', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_visits_society_id'), 'visits', ['society_id'], unique=False)
    op.create_index(op.f('ix_visits_visitor_id'), 'visits', ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visitor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_society_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_occupancy_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_visitors_society_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
