"""clearance and notifications

Revision ID: dd6e2cf8b483
Revises: 1ce832239fa5
Create Date: 2026-09-27 22:35:12.084339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6e2cf8b483'
down_revision: Union[str, Sequence[str], None] = '1ce832239fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dues_clear', sa.Boolean(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearances_id'), 'clearances', ['id'], unique=False)
    op.create_index(op.f('ix_clearances_occupancy_id'), 'clearances', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_clearances_society_id'), 'clearances', ['society_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancies.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_occupancy_id'), 'notifications', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_notifications_society_id'), 'notifications', ['society_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('clearance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clearance_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clearance_id'], ['clearances.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clearance_documents_clearance_id'), 'clearance_documents', ['clearance_id'], unique=False)
    op.create_index(op.f('ix_clearance_documents_id'), 'clearance_documents', ['id'], unique=False)
    op.create_index(op.f('ix_clearance_documents_society_id'), 'clearance_documents', ['society_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_clearance_documents_society_id'), table_name='clearance_documents')
    op.drop_index(op.f('ix_clearance_documents_id'), table_name='clearance_documents')
    op.drop_index(op.f('ix_clearance_documents_clearance_id'), table_name='clearance_documents')
    op.drop_table('clearance_documents')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_society_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_occupancy_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_clearances_society_id'), table_name='clearances')
    op.drop_index(op.f('ix_clearances_occupancy_id'), table_name='clearances')
    op.drop_index(op.f('ix_clearances_id'), table_name='clearances')
    op.drop_table('clearances')
    # ### end Alembic commands ###
