"""vehicles and parking

Revision ID: fe4b60ff4236
Revises: c0b972d2d196
Create Date: 2026-09-27 22:03:41.536306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4b60ff4236'
down_revision: Union[str, Sequence[str], None] = 'c0b972d2d196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ##
    # ### end Alembic commands ###
